# Dataset config for YOLOv8n drone fine-tuning
# ---------------------------------------------
# Single-class drone detector.
# Labels must use class index 0.

train: ../datasets/drone_detect/images/train
val:   ../datasets/drone_detect/images/val

# ~~81 classes: 80 COCO + 1 drone~~
#CHANGED TO 1 (only detecting drone)
nc: 1

names: [drone]